from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class StateStore(Protocol):
    async def ensure_user(
        self, external_auth_id: str | None, email: str | None = None
    ) -> dict[str, Any]: ...
    async def get_user_by_api_key_hash(self, key_hash: str) -> dict[str, Any] | None: ...
    async def create_api_key(
        self, user_id: str, key_hash: str, label: str | None = None
    ) -> dict[str, Any]: ...
    async def revoke_api_key(self, user_id: str, key_id: str) -> bool: ...
    async def list_api_keys(self, user_id: str) -> list[dict[str, Any]]: ...
    async def create_project(
        self, user_id: str, name: str, base_preset: str = "custom"
    ) -> dict[str, Any]: ...
    async def get_project(self, user_id: str, project_id: str) -> dict[str, Any] | None: ...
    async def list_projects(self, user_id: str) -> list[dict[str, Any]]: ...
    async def set_project_status(self, project_id: str, status: str) -> None: ...
    async def delete_project(self, user_id: str, project_id: str) -> bool: ...
    async def rename_project(
        self, user_id: str, project_id: str, name: str
    ) -> dict[str, Any] | None: ...
    async def get_project_config(self, project_id: str) -> dict[str, Any] | None: ...
    async def upsert_project_config(self, project_id: str, **fields: Any) -> dict[str, Any]: ...
    async def register_document(
        self,
        project_id: str,
        filename: str,
        chunk_count: int,
        embedding_signature: str,
        status: str = "ready",
        *,
        size_bytes: int | None = None,
    ) -> dict[str, Any]: ...
    async def set_document_status(self, project_id: str, filename: str, status: str) -> None: ...
    async def list_documents(self, project_id: str) -> list[dict[str, Any]]: ...
    async def delete_document(self, project_id: str, filename: str) -> bool: ...
    async def upsert_credential(
        self, user_id: str, provider: str, encrypted_key: str, key_hint: str
    ) -> dict[str, Any]: ...
    async def get_credential(self, user_id: str, provider: str) -> dict[str, Any] | None: ...
    async def list_credentials(self, user_id: str) -> list[dict[str, Any]]: ...
    async def delete_credential(self, user_id: str, provider: str) -> bool: ...
    async def upsert_thread(
        self,
        project_id: str,
        session_id: str,
        *,
        npc_name: str | None = None,
        title: str | None = None,
    ) -> dict[str, Any]: ...
    async def get_thread(self, user_id: str, thread_id: str) -> dict[str, Any] | None: ...
    async def get_thread_by_prefix(
        self, project_id: str, prefix_hash: str
    ) -> dict[str, Any] | None: ...
    async def set_thread_prefix(self, thread_id: str, prefix_hash: str) -> None: ...
    async def delete_thread(self, user_id: str, thread_id: str) -> bool: ...
    async def add_message(
        self,
        thread_id: str,
        role: str,
        content: str,
        *,
        model: str | None = None,
        prompt_tokens: int | None = None,
        completion_tokens: int | None = None,
        total_tokens: int | None = None,
    ) -> dict[str, Any]: ...
    async def list_threads(self, project_id: str) -> list[dict[str, Any]]: ...
    async def list_messages(self, thread_id: str, limit: int = 50) -> list[dict[str, Any]]: ...
